
services:
  api:
    build: .
    container_name: transcription_api_app
    env_file:
      - .env
    ports:
      - "8000:8000"

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

